SERVER_PORT: 8443
SERVER_SSL_ENABLED: false
SERVICE_VERSION: 0.0.1
LOG_LEVEL: DEBUG

PROD_MODE: false

HTTP_CALLS_MAX_RETRIES: 3
HTTP_CLIENT_TIMEOUT: 5s

# keys should be in lower case
SUPPORTED_SERVERS: {"callamanger": "CALLAMANGER", "TEST": "TEST"}